ALTER TABLE posts ADD COLUMN IF NOT EXISTS status VARCHAR(100) NOT NULL DEFAULT 'pending';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS fail_reason TEXT;

ALTER TABLE post_contents ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE post_contents ADD COLUMN IF NOT EXISTS fail_reason TEXT;

